export const EIconName = {
  AirDrop: 'AirDrop',
  AngleCircleLeft: 'AngleCircleLeft',
  AngleCircleRight: 'AngleCircleRight',
  BookMark: 'BookMark',
  Close: 'Close',
  Copy: 'Copy',
  DailyLottery: 'DailyLottery',
  Home: 'Home',
  Lottery: 'Lottery',
  MgaToken: 'MgaToken',
  MgcToken: 'MgcToken',
  Transcation: 'Transcation',
  Wallet: 'Wallet',
  Logout: 'Logout',
  Referral: 'Referral',
  Task: 'Task',
  CirclePlus: 'CirclePlus',
  Search: 'Search',
  Menu: 'Menu',
  AngleLeft: 'AngleLeft',
  AngleLineLeft: 'AngleLineLeft',
  AngleRight: 'AngleRight',
  AngleLineRight: 'AngleLineRight',
  Ticket: 'Ticket',
  LotteryYellow: 'LotteryYellow',
  Rank: 'Rank',
  Speaker: 'Speaker',
  Union: 'Union',
  Check: 'Check',
  User: 'User',
  UserGreen: 'UserGreen',
  UnionGreen: 'UnionGreen',
  SpeakerGreen: 'SpeakerGreen',
  Question: 'Question',
  ArrowUp: 'ArrowUp',
  AngleUp: 'AngleUp',
};

export const EIconColor = {
  BLACK: '#000',
  WHITE: '#fff',
  NOBEL: '#B5B5B5',
  GORSE: '#FFF84F',
  DOVE_GRAY: '#666666',
};
